name: CI

on:
  push:
    branches: ['main']
    paths-ignore: ['docs/**']


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: uv run pytest --record-mode=none --cov-report term:skip-covered --cov-fail-under=100  --record-mode=none --block-network

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check formatting
        run: uv run ruff format --check

      - name: Lint code with ruff
        run: uv run ruff check

      - name: Check type hints with mypy
        run: uv run mypy --strict

      - name: Check type hints with pyright
        run: uv run pyright